name: Python package

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up uv and Python 3.9
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.9'

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
